# Generated by Django 5.0.6 on 2024-09-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_quizquestion_quizoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizoption',
            name='option_text',
        ),
        migrations.AddField(
            model_name='quizoption',
            name='option1',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='option2',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='option3',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='option4',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
