# Generated by Django 5.0.6 on 2024-09-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_quizoption_option_text_quizoption_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='course',
            field=models.CharField(default='unknown course', max_length=255),
        ),
    ]
